name: My First Manual Workflow
on: [workflow_dispatch]
jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: JMeter
        run: |
            wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.3.tgz
            tar xf apache-jmeter-5.3.tgz
            ls -la
            sudo apt-get update
            sudo apt install openjdk-8-jdk
            ./apache-jmeter-5.3/bin/jmeter.sh  -n –t mytest.jmx -l testresults.jtl
            while [ : ]
            do
              cat testresults.jtl
            done
